{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pymongo\n",
    "from pymongo import MongoClient\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "connection_string = 'mongodb+srv://CnBUser:<password>@cluster0.n2pbusl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "client = MongoClient(connection_string)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "db = client['APS_Project']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "collection = db[\"monog_class\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "data = {\n",
    "    'name':'Darshan',\n",
    "    'age':'24'\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<pymongo.results.InsertOneResult at 0x185c5f13910>"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "collection.insert_one(data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'_id': ObjectId('66756b6c5b6ece0b014a5140'), 'name': 'Darshan', 'age': '24'}\n"
     ]
    }
   ],
   "source": [
    "cursor = collection.find({})\n",
    "for i in cursor:\n",
    "    print(i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#compass is the GUI for mongo db "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sensor.utils.main_utils import read_yaml_file"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "file = read_yaml_file('config\\schema.yaml')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "163"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(file['numerical_columns'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "dict_keys(['columns', 'numerical_columns', 'drop_columns'])"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "file.keys()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sensor.entity import artifacts_entity"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "a = artifacts_entity.DataIngestionArtifact"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "ename": "SensorException",
     "evalue": "Error=[Error=[Error=['NoneType' object has no attribute 'train_file_path'] occurred in file [d:\\APS Project\\sensor\\components\\data_validation.py] on line number [97]] occurred in file [d:\\APS Project\\sensor\\pipeline\\training_pipeline.py] on line number [37]] occurred in file [d:\\APS Project\\sensor\\pipeline\\training_pipeline.py] on line number [48]",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "File \u001b[1;32md:\\APS Project\\sensor\\components\\data_validation.py:97\u001b[0m, in \u001b[0;36mDataValidation.initiate_data_validation\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m     96\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m---> 97\u001b[0m     train_file_path \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mdata_ingestion_artifact\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mtrain_file_path\u001b[49m\n\u001b[0;32m     98\u001b[0m     test_file_path \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdata_ingestion_artifact\u001b[38;5;241m.\u001b[39mtest_file_path\n",
      "\u001b[1;31mAttributeError\u001b[0m: 'NoneType' object has no attribute 'train_file_path'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mSensorException\u001b[0m                           Traceback (most recent call last)",
      "File \u001b[1;32md:\\APS Project\\sensor\\pipeline\\training_pipeline.py:37\u001b[0m, in \u001b[0;36mTrainingPipeline.start_data_validation\u001b[1;34m(self, data_ingestion_artifact)\u001b[0m\n\u001b[0;32m     36\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdata_validation \u001b[38;5;241m=\u001b[39m DataValidation(data_ingestion_artifact\u001b[38;5;241m=\u001b[39mdata_ingestion_artifact,data_validation_config\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdata_validation_config)\n\u001b[1;32m---> 37\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdata_validation_artifact \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mdata_validation\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43minitiate_data_validation\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     38\u001b[0m logging\u001b[38;5;241m.\u001b[39minfo(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mData validation completed and artifact: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdata_validation_artifact\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[1;32md:\\APS Project\\sensor\\components\\data_validation.py:154\u001b[0m, in \u001b[0;36mDataValidation.initiate_data_validation\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    153\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m--> 154\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m SensorException(e,sys)\n",
      "\u001b[1;31mSensorException\u001b[0m: Error=['NoneType' object has no attribute 'train_file_path'] occurred in file [d:\\APS Project\\sensor\\components\\data_validation.py] on line number [97]",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mSensorException\u001b[0m                           Traceback (most recent call last)",
      "File \u001b[1;32md:\\APS Project\\sensor\\pipeline\\training_pipeline.py:48\u001b[0m, in \u001b[0;36mTrainingPipeline.run_pipeline\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m     47\u001b[0m data_ingestion_artifact:DataIngestionArtifact \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mstart_data_ingestion()\n\u001b[1;32m---> 48\u001b[0m data_validation_artifact: DataValidationArtifact \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mstart_data_validation\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdata_ingestion_artifact\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     49\u001b[0m logging\u001b[38;5;241m.\u001b[39minfo(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtraining pipeline completed\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[1;32md:\\APS Project\\sensor\\pipeline\\training_pipeline.py:42\u001b[0m, in \u001b[0;36mTrainingPipeline.start_data_validation\u001b[1;34m(self, data_ingestion_artifact)\u001b[0m\n\u001b[0;32m     41\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m---> 42\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m SensorException(e,sys)\n",
      "\u001b[1;31mSensorException\u001b[0m: Error=[Error=['NoneType' object has no attribute 'train_file_path'] occurred in file [d:\\APS Project\\sensor\\components\\data_validation.py] on line number [97]] occurred in file [d:\\APS Project\\sensor\\pipeline\\training_pipeline.py] on line number [37]",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mSensorException\u001b[0m                           Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[22], line 3\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01msensor\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mpipeline\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mtraining_pipeline\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m TrainingPipeline\n\u001b[0;32m      2\u001b[0m pp1 \u001b[38;5;241m=\u001b[39m TrainingPipeline() \n\u001b[1;32m----> 3\u001b[0m \u001b[43mpp1\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun_pipeline\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32md:\\APS Project\\sensor\\pipeline\\training_pipeline.py:52\u001b[0m, in \u001b[0;36mTrainingPipeline.run_pipeline\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m     50\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m data_ingestion_artifact,data_validation_artifact\n\u001b[0;32m     51\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m---> 52\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m SensorException(e,sys)\n",
      "\u001b[1;31mSensorException\u001b[0m: Error=[Error=[Error=['NoneType' object has no attribute 'train_file_path'] occurred in file [d:\\APS Project\\sensor\\components\\data_validation.py] on line number [97]] occurred in file [d:\\APS Project\\sensor\\pipeline\\training_pipeline.py] on line number [37]] occurred in file [d:\\APS Project\\sensor\\pipeline\\training_pipeline.py] on line number [48]"
     ]
    }
   ],
   "source": [
    "from sensor.pipeline.training_pipeline import TrainingPipeline\n",
    "pp1 = TrainingPipeline() \n",
    "pp1.run_pipeline()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "'NoneType' object has no attribute '__dict__'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[10], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[43mpp1\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mdata_ingestion_artifact\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[38;5;18;43m__dict__\u001b[39;49m\n",
      "\u001b[1;31mAttributeError\u001b[0m: 'NoneType' object has no attribute '__dict__'"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv('data.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "171"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(df.columns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "ename": "SensorException",
     "evalue": "Error=[Error=[Error=[Train files has different number of columns] occurred in file [d:\\APS Project\\sensor\\components\\data_validation.py] on line number [111]] occurred in file [d:\\APS Project\\sensor\\pipeline\\training_pipeline.py] on line number [37]] occurred in file [d:\\APS Project\\sensor\\pipeline\\training_pipeline.py] on line number [48]",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mException\u001b[0m                                 Traceback (most recent call last)",
      "File \u001b[1;32md:\\APS Project\\sensor\\components\\data_validation.py:111\u001b[0m, in \u001b[0;36mDataValidation.initiate_data_validation\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    110\u001b[0m     error_message \u001b[38;5;241m=\u001b[39m \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mTrain files has different number of columns\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m--> 111\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m(error_message)\n\u001b[0;32m    113\u001b[0m status \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mvalidate_number_of_columns(dataframe\u001b[38;5;241m=\u001b[39mtest_dataframe)\n",
      "\u001b[1;31mException\u001b[0m: Train files has different number of columns",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mSensorException\u001b[0m                           Traceback (most recent call last)",
      "File \u001b[1;32md:\\APS Project\\sensor\\pipeline\\training_pipeline.py:37\u001b[0m, in \u001b[0;36mTrainingPipeline.start_data_validation\u001b[1;34m(self, data_ingestion_artifact)\u001b[0m\n\u001b[0;32m     36\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdata_validation \u001b[38;5;241m=\u001b[39m DataValidation(data_ingestion_artifact\u001b[38;5;241m=\u001b[39mdata_ingestion_artifact,data_validation_config\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdata_validation_config)\n\u001b[1;32m---> 37\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdata_validation_artifact \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mdata_validation\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43minitiate_data_validation\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     38\u001b[0m logging\u001b[38;5;241m.\u001b[39minfo(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mData validation completed and artifact: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdata_validation_artifact\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[1;32md:\\APS Project\\sensor\\components\\data_validation.py:156\u001b[0m, in \u001b[0;36mDataValidation.initiate_data_validation\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    155\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m--> 156\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m SensorException(e,sys)\n",
      "\u001b[1;31mSensorException\u001b[0m: Error=[Train files has different number of columns] occurred in file [d:\\APS Project\\sensor\\components\\data_validation.py] on line number [111]",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mSensorException\u001b[0m                           Traceback (most recent call last)",
      "File \u001b[1;32md:\\APS Project\\sensor\\pipeline\\training_pipeline.py:48\u001b[0m, in \u001b[0;36mTrainingPipeline.run_pipeline\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m     47\u001b[0m data_ingestion_artifact:DataIngestionArtifact \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mstart_data_ingestion()\n\u001b[1;32m---> 48\u001b[0m data_validation_artifact: DataValidationArtifact \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mstart_data_validation\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdata_ingestion_artifact\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     49\u001b[0m logging\u001b[38;5;241m.\u001b[39minfo(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtraining pipeline completed\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[1;32md:\\APS Project\\sensor\\pipeline\\training_pipeline.py:42\u001b[0m, in \u001b[0;36mTrainingPipeline.start_data_validation\u001b[1;34m(self, data_ingestion_artifact)\u001b[0m\n\u001b[0;32m     41\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m---> 42\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m SensorException(e,sys)\n",
      "\u001b[1;31mSensorException\u001b[0m: Error=[Error=[Train files has different number of columns] occurred in file [d:\\APS Project\\sensor\\components\\data_validation.py] on line number [111]] occurred in file [d:\\APS Project\\sensor\\pipeline\\training_pipeline.py] on line number [37]",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mSensorException\u001b[0m                           Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[10], line 3\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01msensor\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mpipeline\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mtraining_pipeline\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m TrainingPipeline\n\u001b[0;32m      2\u001b[0m pp1 \u001b[38;5;241m=\u001b[39m TrainingPipeline()\n\u001b[1;32m----> 3\u001b[0m \u001b[43mpp1\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun_pipeline\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32md:\\APS Project\\sensor\\pipeline\\training_pipeline.py:52\u001b[0m, in \u001b[0;36mTrainingPipeline.run_pipeline\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m     50\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m data_ingestion_artifact,data_validation_artifact\n\u001b[0;32m     51\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m---> 52\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m SensorException(e,sys)\n",
      "\u001b[1;31mSensorException\u001b[0m: Error=[Error=[Error=[Train files has different number of columns] occurred in file [d:\\APS Project\\sensor\\components\\data_validation.py] on line number [111]] occurred in file [d:\\APS Project\\sensor\\pipeline\\training_pipeline.py] on line number [37]] occurred in file [d:\\APS Project\\sensor\\pipeline\\training_pipeline.py] on line number [48]"
     ]
    }
   ],
   "source": [
    "from sensor.pipeline.training_pipeline import TrainingPipeline\n",
    "pp1 = TrainingPipeline()\n",
    "pp1.run_pipeline()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv('data.csv')\n",
    "df_og = pd.read_csv('data_0.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [],
   "source": [
    "x_null =df.isnull().mean()\n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [],
   "source": [
    "x_null_df = pd.DataFrame(x_null).reset_index()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "#x_null_df.rename(columns = {'index':'columns',0:'null_values'},inplace = True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(<Axes: xlabel='columns'>, (171, 2))"
      ]
     },
     "execution_count": 45,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAjcAAAGxCAYAAACeKZf2AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuNSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/xnp5ZAAAACXBIWXMAAA9hAAAPYQGoP6dpAAAzMElEQVR4nO3deVjVVeLH8c9lB/GCKIIUihkq5kJhItaMjfJEjdWQNipZqePkWNpUpCbl1qpto85oOU1T1hRZNpPzG8csB7VNNMUlUzRrNBoVsBRwBYTz+8PHWzcBUbksx/free6j9/s953zPOd7l43e7DmOMEQAAgCW8GroDAAAAdYlwAwAArEK4AQAAViHcAAAAqxBuAACAVQg3AADAKoQbAABgFcINAACwik9Dd6AhVFZWau/evWrevLkcDkdDdwcAANSCMUaHDh1SVFSUvLyq3z9zQYabvXv3Kjo6uqG7AQAAzsG3336riy++uNr1F2S4ad68uaSTk+N0Ohu4NwAAoDZKSkoUHR3t+h6vzgUZbk4dinI6nYQbAACamDOdUsIJxQAAwCqEGwAAYBXCDQAAsMoFec4NAKBpqKysVFlZWUN3A/XE19dX3t7e590O4QYA0CiVlZVp165dqqysbOiuoB6FhoYqMjLyvO5DR7gBADQ6xhjt27dP3t7eio6OrvGGbbCDMUZHjx5VYWGhJKlNmzbn3BbhBgDQ6Jw4cUJHjx5VVFSUgoKCGro7qCeBgYGSpMLCQrVu3fqcD1ERhQEAjU5FRYUkyc/Pr4F7gvp2KsyWl5efcxuEGwBAo8Xv/1146uLfnHADAACsQrgBAKCRWLVqlRwOh4qKiiRJCxYsUGhoaL1tf8SIEUpNTa237XkK4QYAAFiFcAMAAKxCuAEAoI5cc801+v3vf6+JEycqLCxMkZGRmj59uiRp9+7dcjgc2rRpk6t8UVGRHA6HVq1adV7b/fLLL+VwOLR9+3a35bNmzVKHDh0knbwCbdSoUWrfvr0CAwPVqVMnzZkzp8Z2Y2JiNHv2bLdl8fHxrjGdGsNvf/tbhYeHy+l0ql+/ftq8ebNr/ebNm/WLX/xCzZs3l9PpVEJCgtavX39e4z0T7nMDAGj0jDE6Vl7RINsO9PU+qyt4Xn31VaWnp2vt2rXKzs7WiBEjdNVVVyk2NtZjfezYsaN69uypN954Q4899phr+RtvvKFbb71V0smfsrj44ou1aNEitWzZUqtXr9bo0aPVpk0bDR48+Jy3/etf/1qBgYF67733FBISoj//+c/q37+/vvzyS4WFhWnYsGG6/PLL9cILL8jb21ubNm2Sr6/veY+5JoQbAECjd6y8Ql2mvt8g2972aIqC/Gr/ddm9e3dNmzZNkhQbG6u5c+cqKyvLo+FGkoYNG6a5c+e6ws2XX36pnJwcvf7665JO/m7TI4884irfvn17ZWdn6+233z7ncPPJJ5/os88+U2Fhofz9/SVJzz77rBYvXqx33nlHo0ePVl5eniZMmKDOnTtLksfnQeKwFAAAdap79+5uz9u0aeP6SQFPGjp0qHbv3q01a9ZIOrnX5oorrnCFCkmaN2+eEhISFB4eruDgYL344ovKy8s7521u3rxZhw8fVsuWLRUcHOx67Nq1S19//bUkKT09Xb/97W+VnJysmTNnupZ7EntuAACNXqCvt7Y9mtJg2z4bPz3k4nA4VFlZ6fp9LGOMa9353IX3pyIjI9WvXz9lZmaqd+/eyszM1F133eVav3DhQo0fP17PPfeckpKS1Lx5cz3zzDNau3ZttW16eXm59fenfT58+LDatGlT5TlDpy5hnz59um699Vb9+9//1nvvvadp06Zp4cKFuvnmm89vwDUg3AAAGj2Hw3FWh4Yao/DwcEnSvn37dPnll0uS28nFdWHYsGGaOHGi0tLS9N///ldDhw51rfv000/Vp08f3X333a5lZ9qLEh4ern379rmel5SUaNeuXa7nV1xxhfLz8+Xj46OYmJhq2+nYsaM6duyo+++/X2lpaXrllVc8Gm44LAUAQD0IDAxU7969NXPmTOXm5urDDz/U5MmT63QbAwcO1KFDh3TXXXfpF7/4haKiolzrYmNjtX79er3//vv68ssvNWXKFK1bt67G9vr166e//e1v+vjjj7VlyxYNHz7c7ccsk5OTlZSUpNTUVH3wwQfavXu3Vq9erYcffljr16/XsWPHNG7cOK1atUrffPONPv30U61bt05xcXF1Ou6fItwAAFBPXn75ZZ04cUIJCQm677779Pjjj9dp+82bN9eNN96ozZs3a9iwYW7rfve732ngwIEaMmSIEhMT9f3337vtxalKRkaG+vbtqxtuuEEDBgxQamqq69Jy6eQetaVLl+rnP/+5Ro4cqY4dO2ro0KH65ptvFBERIW9vb33//fe644471LFjRw0ePFjXX3+924nNnuAwPz2YdgEoKSlRSEiIiouL5XQ6G7o7AICfOH78uHbt2qX27dsrICCgobuDelTTv31tv7/ZcwMAAKxCuAEAoAm47LLL3C63/vHjjTfeaOjuNSpN+9RzAAAuEEuXLq320vGIiIh67k3jRrgBAKAJaNeuXUN3ocngsBQAoNG6AK95ueDVxb854QYA0OicupdKWVlZA/cE9e3o0aOSTr/T89ngsBQAoNHx8fFRUFCQ9u/fL19fX9dPF8BexhgdPXpUhYWFCg0NdbtZ4Nki3AAAGh2Hw6E2bdpo165d+uabbxq6O6hHoaGhioyMPK82CDcAgEbJz89PsbGxHJq6gPj6+p7XHptTCDcAgEbLy8uLOxTjrHEQEwAAWIVwAwAArEK4AQAAViHcAAAAqxBuAACAVQg3AADAKoQbAABgFcINAACwCuEGAABYhXADAACsQrgBAABWqZdwM2/ePMXExCggIECJiYn67LPPaiy/aNEide7cWQEBAerWrZuWLl1abdkxY8bI4XBo9uzZddxrAADQFHk83Lz11ltKT0/XtGnTtGHDBvXo0UMpKSkqLCyssvzq1auVlpamUaNGaePGjUpNTVVqaqq++OKL08q+++67WrNmjaKiojw9DAAA0ER4PNz84Q9/0J133qmRI0eqS5cumj9/voKCgvTyyy9XWX7OnDm67rrrNGHCBMXFxemxxx7TFVdcoblz57qV27Nnj+655x698cYb8vX19fQwAABAE+HRcFNWVqacnBwlJyf/sEEvLyUnJys7O7vKOtnZ2W7lJSklJcWtfGVlpW6//XZNmDBBl1122Rn7UVpaqpKSErcHAACwk0fDzXfffaeKigpFRES4LY+IiFB+fn6VdfLz889Y/qmnnpKPj49+//vf16ofM2bMUEhIiOsRHR19liMBAABNRZO7WionJ0dz5szRggUL5HA4alUnIyNDxcXFrse3337r4V4CAICG4tFw06pVK3l7e6ugoMBteUFBgSIjI6usExkZWWP5jz/+WIWFhWrbtq18fHzk4+Ojb775Rg888IBiYmKqbNPf319Op9PtAQAA7OTRcOPn56eEhARlZWW5llVWViorK0tJSUlV1klKSnIrL0nLly93lb/99tv1+eefa9OmTa5HVFSUJkyYoPfff99zgwEAAE2Cj6c3kJ6eruHDh6tnz57q1auXZs+erSNHjmjkyJGSpDvuuEMXXXSRZsyYIUm699571bdvXz333HMaMGCAFi5cqPXr1+vFF1+UJLVs2VItW7Z024avr68iIyPVqVMnTw8HAAA0ch4PN0OGDNH+/fs1depU5efnKz4+XsuWLXOdNJyXlycvrx92IPXp00eZmZmaPHmyHnroIcXGxmrx4sXq2rWrp7sKAAAs4DDGmIbuRH0rKSlRSEiIiouLOf8GAIAmorbf303uaikAAICaEG4AAIBVCDcAAMAqhBsAAGAVwg0AALAK4QYAAFiFcAMAAKxCuAEAAFYh3AAAAKsQbgAAgFUINwAAwCqEGwAAYBXCDQAAsArhBgAAWIVwAwAArEK4AQAAViHcAAAAqxBuAACAVQg3AADAKoQbAABgFcINAACwCuEGAABYhXADAACsQrgBAABWIdwAAACrEG4AAIBVCDcAAMAqhBsAAGAVwg0AALAK4QYAAFiFcAMAAKxCuAEAAFYh3AAAAKsQbgAAgFUINwAAwCqEGwAAYBXCDQAAsArhBgAAWIVwAwAArEK4AQAAViHcAAAAqxBuAACAVQg3AADAKoQbAABgFcINAACwCuEGAABYhXADAACsQrgBAABWIdwAAACrEG4AAIBVCDcAAMAqhBsAAGAVwg0AALAK4QYAAFiFcAMAAKxCuAEAAFapl3Azb948xcTEKCAgQImJifrss89qLL9o0SJ17txZAQEB6tatm5YuXepaV15ergcffFDdunVTs2bNFBUVpTvuuEN79+719DAAAEAT4PFw89Zbbyk9PV3Tpk3Thg0b1KNHD6WkpKiwsLDK8qtXr1ZaWppGjRqljRs3KjU1Vampqfriiy8kSUePHtWGDRs0ZcoUbdiwQf/4xz+0Y8cO3XTTTZ4eCgAAaAIcxhjjyQ0kJibqyiuv1Ny5cyVJlZWVio6O1j333KNJkyadVn7IkCE6cuSIlixZ4lrWu3dvxcfHa/78+VVuY926derVq5e++eYbtW3b9ox9KikpUUhIiIqLi+V0Os9xZAAAoD7V9vvbo3tuysrKlJOTo+Tk5B826OWl5ORkZWdnV1knOzvbrbwkpaSkVFtekoqLi+VwOBQaGlon/QYAAE2Xjycb/+6771RRUaGIiAi35REREdq+fXuVdfLz86ssn5+fX2X548eP68EHH1RaWlq1Ka60tFSlpaWu5yUlJWczDAAA0IQ06aulysvLNXjwYBlj9MILL1RbbsaMGQoJCXE9oqOj67GXAACgPnk03LRq1Ure3t4qKChwW15QUKDIyMgq60RGRtaq/Klg880332j58uU1HnvLyMhQcXGx6/Htt9+e44gAAEBj59Fw4+fnp4SEBGVlZbmWVVZWKisrS0lJSVXWSUpKcisvScuXL3crfyrY7Ny5U//5z3/UsmXLGvvh7+8vp9Pp9gAAAHby6Dk3kpSenq7hw4erZ8+e6tWrl2bPnq0jR45o5MiRkqQ77rhDF110kWbMmCFJuvfee9W3b18999xzGjBggBYuXKj169frxRdflHQy2Nxyyy3asGGDlixZooqKCtf5OGFhYfLz8/P0kAAAQCPm8XAzZMgQ7d+/X1OnTlV+fr7i4+O1bNky10nDeXl58vL6YQdSnz59lJmZqcmTJ+uhhx5SbGysFi9erK5du0qS9uzZo//7v/+TJMXHx7tta+XKlbrmmms8PSQAANCIefw+N40R97kBAKDpaRT3uQEAAKhvhBsAAGAVwg0AALAK4QYAAFiFcAMAAKxCuAEAAFYh3AAAAKsQbgAAgFUINwAAwCqEGwAAYBXCDQAAsArhBgAAWIVwAwAArEK4AQAAViHcAAAAqxBuAACAVQg3AADAKoQbAABgFcINAACwCuEGAABYhXADAACsQrgBAABWIdwAAACrEG4AAIBVCDcAAMAqhBsAAGAVwg0AALAK4QYAAFiFcAMAAKxCuAEAAFYh3AAAAKsQbgAAgFUINwAAwCqEGwAAYBXCDQAAsArhBgAAWIVwAwAArEK4AQAAViHcAAAAqxBuAACAVQg3AADAKoQbAABgFcINAACwCuEGAABYhXADAACsQrgBAABWIdwAAACrEG4AAIBVCDcAAMAqhBsAAGAVwg0AALAK4QYAAFiFcAMAAKxCuAEAAFYh3AAAAKsQbgAAgFXqJdzMmzdPMTExCggIUGJioj777LMayy9atEidO3dWQECAunXrpqVLl7qtN8Zo6tSpatOmjQIDA5WcnKydO3d6cggAAKCJ8Hi4eeutt5Senq5p06Zpw4YN6tGjh1JSUlRYWFhl+dWrVystLU2jRo3Sxo0blZqaqtTUVH3xxReuMk8//bT++Mc/av78+Vq7dq2aNWumlJQUHT9+3NPDAQAAjZzDGGM8uYHExERdeeWVmjt3riSpsrJS0dHRuueeezRp0qTTyg8ZMkRHjhzRkiVLXMt69+6t+Ph4zZ8/X8YYRUVF6YEHHtD48eMlScXFxYqIiNCCBQs0dOjQM/appKREISEhKi4ultPprKORAgAAT6rt97ePJztRVlamnJwcZWRkuJZ5eXkpOTlZ2dnZVdbJzs5Wenq627KUlBQtXrxYkrRr1y7l5+crOTnZtT4kJESJiYnKzs6uVbjxFGOMjpVXNNj2AQBoLAJ9veVwOBpk2x4NN999950qKioUERHhtjwiIkLbt2+vsk5+fn6V5fPz813rTy2rrsxPlZaWqrS01PW8pKTk7AZSS8fKK9Rl6vseaRsAgKZk26MpCvLzaMyo1gVxtdSMGTMUEhLiekRHRzd0lwAAgId4NFK1atVK3t7eKigocFteUFCgyMjIKutERkbWWP7UnwUFBWrTpo1bmfj4+CrbzMjIcDvUVVJS4pGAE+jrrW2PptR5uwAANDWBvt4Ntm2Phhs/Pz8lJCQoKytLqampkk6eUJyVlaVx48ZVWScpKUlZWVm67777XMuWL1+upKQkSVL79u0VGRmprKwsV5gpKSnR2rVrddddd1XZpr+/v/z9/etsXNVxOBwNtgsOAACc5PFv4vT0dA0fPlw9e/ZUr169NHv2bB05ckQjR46UJN1xxx266KKLNGPGDEnSvffeq759++q5557TgAEDtHDhQq1fv14vvviipJMB4r777tPjjz+u2NhYtW/fXlOmTFFUVJQrQAEAgAuXx8PNkCFDtH//fk2dOlX5+fmKj4/XsmXLXCcE5+Xlycvrh1N/+vTpo8zMTE2ePFkPPfSQYmNjtXjxYnXt2tVVZuLEiTpy5IhGjx6toqIiXX311Vq2bJkCAgI8PRwAANDIefw+N40R97kBAKDpqe339wVxtRQAALhwEG4AAIBVCDcAAMAqhBsAAGAVwg0AALAK4QYAAFiFcAMAAKxCuAEAAFYh3AAAAKsQbgAAgFUINwAAwCqEGwAAYBXCDQAAsArhBgAAWIVwAwAArEK4AQAAViHcAAAAqxBuAACAVQg3AADAKoQbAABgFcINAACwCuEGAABYhXADAACsQrgBAABWIdwAAACrEG4AAIBVCDcAAMAqhBsAAGAVwg0AALAK4QYAAFiFcAMAAKxCuAEAAFYh3AAAAKsQbgAAgFUINwAAwCqEGwAAYBXCDQAAsArhBgAAWIVwAwAArEK4AQAAViHcAAAAqxBuAACAVQg3AADAKoQbAABgFcINAACwCuEGAABYhXADAACsQrgBAABWIdwAAACrEG4AAIBVCDcAAMAqhBsAAGAVwg0AALAK4QYAAFiFcAMAAKxCuAEAAFbxWLg5cOCAhg0bJqfTqdDQUI0aNUqHDx+usc7x48c1duxYtWzZUsHBwRo0aJAKCgpc6zdv3qy0tDRFR0crMDBQcXFxmjNnjqeGAAAAmiCPhZthw4Zp69atWr58uZYsWaKPPvpIo0ePrrHO/fffr3/9619atGiRPvzwQ+3du1cDBw50rc/JyVHr1q31+uuva+vWrXr44YeVkZGhuXPnemoYAACgiXEYY0xdN5qbm6suXbpo3bp16tmzpyRp2bJl+uUvf6n//e9/ioqKOq1OcXGxwsPDlZmZqVtuuUWStH37dsXFxSk7O1u9e/eucltjx45Vbm6uVqxYUev+lZSUKCQkRMXFxXI6necwQgAAUN9q+/3tkT032dnZCg0NdQUbSUpOTpaXl5fWrl1bZZ2cnByVl5crOTnZtaxz585q27atsrOzq91WcXGxwsLC6q7zAACgSfPxRKP5+flq3bq1+4Z8fBQWFqb8/Pxq6/j5+Sk0NNRteURERLV1Vq9erbfeekv//ve/a+xPaWmpSktLXc9LSkpqMQoAANAUndWem0mTJsnhcNT42L59u6f66uaLL77Qr371K02bNk3XXnttjWVnzJihkJAQ1yM6Orpe+ggAAOrfWe25eeCBBzRixIgay1xyySWKjIxUYWGh2/ITJ07owIEDioyMrLJeZGSkysrKVFRU5Lb3pqCg4LQ627ZtU//+/TV69GhNnjz5jP3OyMhQenq663lJSQkBBwAAS51VuAkPD1d4ePgZyyUlJamoqEg5OTlKSEiQJK1YsUKVlZVKTEyssk5CQoJ8fX2VlZWlQYMGSZJ27NihvLw8JSUlucpt3bpV/fr10/Dhw/XEE0/Uqt/+/v7y9/evVVkAANC0eeRqKUm6/vrrVVBQoPnz56u8vFwjR45Uz549lZmZKUnas2eP+vfvr9dee029evWSJN11111aunSpFixYIKfTqXvuuUfSyXNrpJOHovr166eUlBQ988wzrm15e3vXKnSdwtVSAAA0PbX9/vbICcWS9MYbb2jcuHHq37+/vLy8NGjQIP3xj390rS8vL9eOHTt09OhR17JZs2a5ypaWliolJUXPP/+8a/0777yj/fv36/XXX9frr7/uWt6uXTvt3r3bU0MBAABNiMf23DRm7LkBAKDpadD73AAAADQUwg0AALAK4QYAAFiFcAMAAKxCuAEAAFYh3AAAAKsQbgAAgFUINwAAwCqEGwAAYBXCDQAAsArhBgAAWIVwAwAArEK4AQAAViHcAAAAqxBuAACAVQg3AADAKoQbAABgFcINAACwCuEGAABYhXADAACsQrgBAABWIdwAAACrEG4AAIBVCDcAAMAqhBsAAGAVwg0AALAK4QYAAFiFcAMAAKxCuAEAAFYh3AAAAKsQbgAAgFUINwAAwCqEGwAAYBXCDQAAsArhBgAAWIVwAwAArEK4AQAAViHcAAAAqxBuAACAVQg3AADAKoQbAABgFcINAACwCuEGAABYhXADAACsQrgBAABWIdwAAACrEG4AAIBVCDcAAMAqhBsAAGAVwg0AALAK4QYAAFiFcAMAAKxCuAEAAFYh3AAAAKsQbgAAgFUINwAAwCqEGwAAYBWPhZsDBw5o2LBhcjqdCg0N1ahRo3T48OEa6xw/flxjx45Vy5YtFRwcrEGDBqmgoKDKst9//70uvvhiORwOFRUVeWAEAACgKfJYuBk2bJi2bt2q5cuXa8mSJfroo480evToGuvcf//9+te//qVFixbpww8/1N69ezVw4MAqy44aNUrdu3f3RNcBAEAT5jDGmLpuNDc3V126dNG6devUs2dPSdKyZcv0y1/+Uv/73/8UFRV1Wp3i4mKFh4crMzNTt9xyiyRp+/btiouLU3Z2tnr37u0q+8ILL+itt97S1KlT1b9/fx08eFChoaG17l9JSYlCQkJUXFwsp9N5foMFAAD1orbf3x7Zc5Odna3Q0FBXsJGk5ORkeXl5ae3atVXWycnJUXl5uZKTk13LOnfurLZt2yo7O9u1bNu2bXr00Uf12muvycurdt0vLS1VSUmJ2wMAANjJI+EmPz9frVu3dlvm4+OjsLAw5efnV1vHz8/vtD0wERERrjqlpaVKS0vTM888o7Zt29a6PzNmzFBISIjrER0dfXYDAgAATcZZhZtJkybJ4XDU+Ni+fbun+qqMjAzFxcXptttuO+t6xcXFrse3337roR4CAICG5nM2hR944AGNGDGixjKXXHKJIiMjVVhY6Lb8xIkTOnDggCIjI6usFxkZqbKyMhUVFbntvSkoKHDVWbFihbZs2aJ33nlHknTqdKFWrVrp4Ycf1iOPPFJl2/7+/vL396/NEAEAQBN3VuEmPDxc4eHhZyyXlJSkoqIi5eTkKCEhQdLJYFJZWanExMQq6yQkJMjX11dZWVkaNGiQJGnHjh3Ky8tTUlKSJOnvf/+7jh075qqzbt06/eY3v9HHH3+sDh06nM1QAACApc4q3NRWXFycrrvuOt15552aP3++ysvLNW7cOA0dOtR1pdSePXvUv39/vfbaa+rVq5dCQkI0atQopaenKywsTE6nU/fcc4+SkpJcV0r9NMB89913ru2dzdVSAADAXh4JN5L0xhtvaNy4cerfv7+8vLw0aNAg/fGPf3StLy8v144dO3T06FHXslmzZrnKlpaWKiUlRc8//7ynuggAACzkkfvcNHbc5wYAgKanQe9zAwAA0FAINwAAwCqEGwAAYBXCDQAAsArhBgAAWIVwAwAArEK4AQAAViHcAAAAqxBuAACAVQg3AADAKoQbAABgFcINAACwCuEGAABYhXADAACsQrgBAABWIdwAAACrEG4AAIBVCDcAAMAqhBsAAGAVwg0AALAK4QYAAFiFcAMAAKxCuAEAAFYh3AAAAKsQbgAAgFUINwAAwCqEGwAAYBXCDQAAsArhBgAAWIVwAwAArEK4AQAAViHcAAAAqxBuAACAVQg3AADAKoQbAABgFcINAACwCuEGAABYhXADAACsQrgBAABWIdwAAACrEG4AAIBVCDcAAMAqhBsAAGAVn4buQEMwxkiSSkpKGrgnAACgtk59b5/6Hq/OBRluDh06JEmKjo5u4J4AAICzdejQIYWEhFS73mHOFH8sVFlZqb1796p58+ZyOBx12nZJSYmio6P17bffyul01mnbTQnzcBLzcBLz8APm4iTm4STm4Qe1mQtjjA4dOqSoqCh5eVV/Zs0FuefGy8tLF198sUe34XQ6L/gXqsQ8nMI8nMQ8/IC5OIl5OIl5+MGZ5qKmPTancEIxAACwCuEGAABYhXBTx/z9/TVt2jT5+/s3dFcaFPNwEvNwEvPwA+biJObhJObhB3U5FxfkCcUAAMBe7LkBAABWIdwAAACrEG7Owu7du+VwOLRp06aG7gpQ56655hrdd999Dd0NoMngPdN4EW7gMXl5eRowYICCgoLUunVrTZgwQSdOnHArs2rVKl1xxRXy9/fXpZdeqgULFpzWzrx58xQTE6OAgAAlJibqs88+q6cR1I0z9f/48eMaO3asWrZsqeDgYA0aNEgFBQWu9QsWLJDD4ajyUVhYWN/DOWcHDhzQsGHD5HQ6FRoaqlGjRunw4cNuZT7//HP97Gc/U0BAgKKjo/X000+f1s6iRYvUuXNnBQQEqFu3blq6dGl9DaHO1MU4jTGaOnWq2rRpo8DAQCUnJ2vnzp31NYQ6wTz8gPdHHTOotV27dhlJZuPGjQ3dlUbvxIkTpmvXriY5Odls3LjRLF261LRq1cpkZGS4yvz3v/81QUFBJj093Wzbts386U9/Mt7e3mbZsmWuMgsXLjR+fn7m5ZdfNlu3bjV33nmnCQ0NNQUFBQ0xrLNWm/6PGTPGREdHm6ysLLN+/XrTu3dv06dPH9f6o0ePmn379rk9UlJSTN++feu0r3379jX33ntvnbb5Y9ddd53p0aOHWbNmjfn444/NpZdeatLS0lzri4uLTUREhBk2bJj54osvzJtvvmkCAwPNn//8Z1eZTz/91Hh7e5unn37abNu2zUyePNn4+vqaLVu2eKzfda2uxjlz5kwTEhJiFi9ebDZv3mxuuukm0759e3Ps2LGGGNZZs2Ee6vI9w/ujbhFuqlBRUWGeeuop06FDB+Pn52eio6PN448/flq4OXHihPnNb35jYmJiTEBAgOnYsaOZPXu2W1srV640V155pQkKCjIhISGmT58+Zvfu3cYYYzZt2mSuueYaExwcbJo3b26uuOIKs27dunob53vvvWeuuuoqExISYsLCwsyAAQPMV199ZYz5Ici9+eabJikpyfj7+5vLLrvMrFq1qlZtL1261Hh5eZn8/HzXshdeeME4nU5TWlpqjDFm4sSJ5rLLLnOrN2TIEJOSkuJ63qtXLzN27FjX84qKChMVFWVmzJhxzuOuSk1zMW3aNCPptMcrr7xyxnbP1P+ioiLj6+trFi1a5CqTm5trJJns7Owq2ywsLDS+vr7mtddeO48Rn65v375m7NixZuzYscbpdJqWLVuayZMnm8rKSmOMMe3atTNPPPGEGTlypAkODjbR0dFuH6w12bZtm5Hk9vp+7733jMPhMHv27DHGGPP888+bFi1auF4fxhjz4IMPmk6dOrmeDx482AwYMMCt7cTERPO73/3unMddnTN9Dvz9738311xzjQkMDDTdu3c3q1evrlW7dTHOyspKExkZaZ555hnX+qKiIuPv72/efPPN8xn2aaqbh5UrVxpJ5uDBg66yGzduNJLMrl27zthuU5uHw4cPm9tvv900a9bMREZGmmeffdYt3Egy7777rludkJCQWn1ONMX3R2PHYakqZGRkaObMmZoyZYq2bdumzMxMRUREnFausrJSF198sRYtWqRt27Zp6tSpeuihh/T2229Lkk6cOKHU1FT17dtXn3/+ubKzszV69GjX71kNGzZMF198sdatW6ecnBxNmjRJvr6+9TbOI0eOKD09XevXr1dWVpa8vLx08803q7Ky0lVmwoQJeuCBB7Rx40YlJSXpxhtv1Pfff3/GtrOzs9WtWze3eUtJSVFJSYm2bt3qKpOcnOxWLyUlRdnZ2ZKksrIy5eTkuJXx8vJScnKyq0xdqWkuxo8fr3379rkezz77rIKCgtSzZ88a26xN/3NyclReXu5WpnPnzmrbtm21Y3zttdcUFBSkW265pQ5G7u7VV1+Vj4+PPvvsM82ZM0d/+MMf9NJLL7nWP/fcc+rZs6c2btyou+++W3fddZd27Nhxxnazs7MVGhrqNmfJycny8vLS2rVrXWV+/vOfy8/Pz1UmJSVFO3bs0MGDB11lanrN1KUzfQ48/PDDGj9+vDZt2qSOHTsqLS3ttMOuVamLce7atUv5+fluZUJCQpSYmFjnc1Hbz8Oz1dTmYcKECfrwww/1z3/+Ux988IFWrVqlDRs21EnbTfH90dhdkL8tVZNDhw5pzpw5mjt3roYPHy5J6tChg66++mrt3r3brayvr68eeeQR1/P27dsrOztbb7/9tgYPHqySkhIVFxfrhhtuUIcOHSRJcXFxrvJ5eXmaMGGCOnfuLEmKjY318OjcDRo0yO35yy+/rPDwcG3btk3BwcGSpHHjxrnKvfDCC1q2bJn++te/auLEiTW2nZ+ff9oH4Knn+fn5NZYpKSnRsWPHdPDgQVVUVFRZZvv27Wc52prVNBddu3Z1zceaNWs0efJkvfrqq+ratWuNbX733Xdn7H9+fr78/PwUGhp6WplT8/RTf/3rX3XrrbcqMDDwbIZYK9HR0Zo1a5YcDoc6deqkLVu2aNasWbrzzjslSb/85S919913S5IefPBBzZo1SytXrlSnTp1qbDc/P1+tW7d2W+bj46OwsDC310P79u3dyvz4NdOiRYtqXzPVzdW5qs3nwPjx4zVgwABJ0iOPPKLLLrtMX331lev9XJ26GOepPz09FzXNw6pVq86r7aY0D4cPH9Zf//pXvf766+rfv7+kk/8RqKvfKGxq74+mgD03P5Gbm6vS0lLXC/hM5s2bp4SEBIWHhys4OFgvvvii8vLyJElhYWEaMWKEUlJSdOONN2rOnDnat2+fq256erp++9vfKjk5WTNnztTXX3/tkTFVZ+fOnUpLS9Mll1wip9OpmJgYSXL1X5KSkpJcf/fx8VHPnj2Vm5tbr/2sD7WZi7y8PKWmpmr8+PEaPHhwg/QzOztbubm5GjVqlEfa7927t2vPonTy33/nzp2qqKiQJHXv3t21zuFwKDIyskmd1Fxbtfkc+PFctGnTRpKsm4uz/Ty01ddff62ysjIlJia6loWFhZ0x1KPhEG5+4mz+N7xw4UKNHz9eo0aN0gcffKBNmzZp5MiRKisrc5V55ZVXlJ2drT59+uitt95Sx44dtWbNGknS9OnTtXXrVg0YMEArVqxQly5d9O6779b5mKpz44036sCBA/rLX/6itWvXunZ//rj/5yoyMtLtih9JrueRkZE1lnE6nQoMDFSrVq3k7e1dZZlTbdSVM83FkSNHdNNNNykpKUmPPvpordqsTf8jIyNVVlamoqKiasv82EsvvaT4+HglJCSc7RDrxE8PmzocDrfDmNWpKgSdOHFCBw4cOOPr4dS6msrU9euhNp8DP56LU4GwtnNxvuM89aen56KmefDyOvn1YX50k/vy8vJat92U5qE2HA6H21xItZ+Ppvb+aAoINz8RGxurwMBAZWVlnbHsp59+qj59+ujuu+/W5ZdfrksvvbTKvS+XX365MjIytHr1anXt2lWZmZmudR07dtT999+vDz74QAMHDtQrr7xSp+Opzvfff68dO3Zo8uTJ6t+/v+Li4lzHbX/sVBCTTr7ZcnJy3A6tVScpKUlbtmxxe8MuX75cTqdTXbp0cZX56TwvX77ctbfIz89PCQkJbmUqKyuVlZXltkfpfJ1pLowxuu2221RZWam//e1vbns2alKb/ickJMjX19etzI4dO5SXl3faGA8fPqy3337bY3ttJLlC3Slr1qxRbGysvL29z6vdpKQkFRUVKScnx7VsxYoVqqysdP1vOCkpSR999JHbF8Ly5cvVqVMntWjRwlWmptdMXTmbz4GzVRfjbN++vSIjI93KlJSUaO3atXU6FzXNQ3h4uCS57Y0+m3uANaV56NChg3x9fd3eHwcPHtSXX37peh4eHu42Fzt37tTRo0dr1X5Te380CQ18QnOjNH36dNOiRQvz6quvmq+++spkZ2ebl1566bSrpebMmWOcTqdZtmyZ2bFjh5k8ebJxOp2mR48expiTlzpPmjTJrF692uzevdu8//77pmXLlub55583R48eNWPHjjUrV640u3fvNp988onp0KGDmThxYr2MsaKiwrRs2dLcdtttZufOnSYrK8tceeWVrjP+T421bdu25h//+IfJzc01o0ePNsHBwWb//v1nbP/UpeDXXnut2bRpk1m2bJkJDw+v8lLwCRMmmNzcXDNv3rwqLwX39/c3CxYsMNu2bTOjR482oaGhbldheXoupk6daoKDg83q1avdLsc+evToGduuTf/HjBlj2rZta1asWGHWr19vkpKSTFJS0mltvfTSSyYgIMDt6pS61LdvXxMcHGzuv/9+s337dpOZmWmaNWtm5s+fb4w5ebXUrFmz3Or06NHDTJs2rVbtX3fddebyyy83a9euNZ988omJjY11u9S1qKjIREREmNtvv9188cUXZuHChSYoKOi0S119fHzMs88+a3Jzc820adM8dqlrbT8HjDHm4MGDRpJZuXLlGdutq3HOnDnThIaGmn/+85/m888/N7/61a88cgl0dfNQVlZmoqOjza9//Wvz5ZdfmiVLlphOnTrV+mqppjYPY8aMMe3atTNZWVlmy5Yt5qabbjLBwcGuq6WGDh1q4uLizIYNG8y6detMv379jK+vb62uljKm6b0/GjvCTRUqKirM448/btq1a2d8fX1N27ZtzZNPPnnah9rx48fNiBEjTEhIiAkNDTV33XWXmTRpkivc5Ofnm9TUVNOmTRvj5+dn2rVrZ6ZOnWoqKipMaWmpGTp0qImOjjZ+fn4mKirKjBs3rl7vUbF8+XITFxdn/P39Tffu3c2qVatOCzeZmZmmV69exs/Pz3Tp0sWsWLGi1u3v3r3bXH/99SYwMNC0atXKPPDAA6a8vNytzMqVK018fLzx8/Mzl1xySZUfBH/6059M27ZtjZ+fn+nVq5dZs2bN+Q79NDXNRd++fc/5UvDa9P/YsWPm7rvvNi1atDBBQUHm5ptvNvv27TutnaSkJHPrrbfWxXCr1LdvX3P33XebMWPGGKfTaVq0aGEeeught0vBzyfcfP/99yYtLc0EBwcbp9NpRo4caQ4dOuRWZvPmzebqq682/v7+5qKLLjIzZ848rZ23337bdOzY0fj5+ZnLLrvM/Pvf/z6n8Z5JbT8HjDm7cGNM3YyzsrLSTJkyxURERBh/f3/Tv39/s2PHjvMZcpWqmwdjjPnkk09Mt27dTEBAgPnZz35mFi1aVOtwY0zTmodDhw6Z2267zQQFBZmIiAjz9NNPu10KvmfPHnPttdeaZs2amdjYWLN06dJaXwpuTNN7fzR2/Co4qrR79261b99eGzduVHx8fEN3BwCAWuOcGwAAYBXCDc7JmDFjFBwcXOVjzJgxDd29epGXl1ftHAQHB7tdRm67J598stp5uP766xu6e/Xq+uuvr3YunnzyyYbuXr1hHn7A+6P+cVgK56SwsFAlJSVVrnM6nafdkMpGJ06cOO3Gjj8WExMjH58L4z6ZBw4c0IEDB6pcFxgYqIsuuqiee9Rw9uzZo2PHjlW5LiwsTGFhYfXco4bBPPyA90f9I9wAAACrcFgKAABYhXADAACsQrgBAABWIdwAAACrEG4ANHojRoxQampqQ3cDQBNBuAEAAFYh3AAAAKsQbgDUi8rKSj399NO69NJL5e/vr7Zt2+qJJ56QJG3ZskX9+vVTYGCgWrZsqdGjR+vw4cPVthUTE6PZs2e7LYuPj9f06dNdzx0Oh/785z/rhhtuUFBQkOLi4pSdna2vvvpK11xzjZo1a6Y+ffro66+/dtWZPn264uPj9be//U0xMTEKCQnR0KFDdejQIVeZd955R926dXP1NTk5WUeOHKmbSQJQJwg3AOpFRkaGZs6cqSlTpmjbtm3KzMxURESEjhw5opSUFLVo0ULr1q3TokWL9J///Efjxo07720+9thjuuOOO7Rp0yZ17txZt956q373u98pIyND69evlzHmtO18/fXXWrx4sZYsWaIlS5boww8/1MyZMyVJ+/btU1pamn7zm98oNzdXq1at0sCBA8W9UIHG5cK4NzyABnXo0CHNmTNHc+fO1fDhwyVJHTp00NVXX62//OUvOn78uF577TU1a9ZMkjR37lzdeOONeuqppxQREXHO2x05cqQGDx4sSXrwwQeVlJSkKVOmKCUlRZJ07733auTIkW51KisrtWDBAjVv3lySdPvttysrK0tPPPGE9u3bpxMnTmjgwIFq166dJKlbt27n3D8AnsGeGwAel5ubq9LSUvXv37/KdT169HAFG0m66qqrVFlZqR07dpzXdrt37+76+6mQ9OMwEhERoePHj7v9TlpMTIwr2EhSmzZtVFhYKEnq0aOH+vfvr27duunXv/61/vKXv+jgwYPn1UcAdY9wA8DjAgMD67Q9Ly+v0w4FlZeXn1bO19fX9XeHw1HtssrKyirrnCpzar23t7eWL1+u9957T126dNGf/vQnderUSbt27TrPEQGoS4QbAB4XGxurwMBAZWVlnbYuLi5Omzdvdjsp99NPP5WXl5c6depUZXvh4eHat2+f63lJSUm9BQyHw6GrrrpKjzzyiDZu3Cg/Pz+9++679bJtALXDOTcAPC4gIEAPPvigJk6cKD8/P1111VXav3+/tm7dqmHDhmnatGkaPny4pk+frv379+uee+7R7bffXu35Nv369dOCBQt04403KjQ0VFOnTpW3t7fHx7F27VplZWXp2muvVevWrbV27Vrt379fcXFxHt82gNoj3ACoF1OmTJGPj4+mTp2qvXv3qk2bNhozZoyCgoL0/vvv695779WVV16poKAgDRo0SH/4wx+qbSsjI0O7du3SDTfcoJCQED322GP1sufG6XTqo48+0uzZs1VSUqJ27drpueee0/XXX+/xbQOoPYfhGkYAAGARzrkBAABWIdwAAACrEG4AAIBVCDcAAMAqhBsAAGAVwg0AALAK4QYAAFiFcAMAAKxCuAEAAFYh3AAAAKsQbgAAgFUINwAAwCr/DwePyyT/UTFFAAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "x_null_df.plot(x = 'columns',y = 'null_values'), x_null_df.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "from scipy.stats import ks_2samp\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "def detect_dataset_drift(base:pd.DataFrame,current:pd.DataFrame,threshold = 0.5) :\n",
    "        try:\n",
    "            status = False\n",
    "            #if status is true, drift is detected\n",
    "            report = dict()\n",
    "\n",
    "            for column in base.columns:\n",
    "                d1 = base[column]\n",
    "                d2 = current[column]\n",
    "                is_same_dist = ks_2samp(d1,d2)\n",
    "\n",
    "                if is_same_dist.pvalue <= threshold :\n",
    "                    drift_in_col = False\n",
    "                else:\n",
    "                    drift_in_col = True\n",
    "                    status = True\n",
    "                report[column] = {\n",
    "                    \"drift_status\":drift_in_col,\n",
    "                    \"p_value\":float(is_same_dist.pvalue)\n",
    "                }\n",
    "            \n",
    "            \n",
    "            \n",
    "            return report,status\n",
    "        except Exception as e:\n",
    "            print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "detect_dataset_drift(df,df_og)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "SensorException",
     "evalue": "Error=[Error=[Error=[only integer scalar arrays can be converted to a scalar index] occurred in file [d:\\APS Project\\sensor\\components\\data_transformation.py] on line number [79]] occurred in file [d:\\APS Project\\sensor\\pipeline\\training_pipeline.py] on line number [50]] occurred in file [d:\\APS Project\\sensor\\pipeline\\training_pipeline.py] on line number [62]",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "File \u001b[1;32md:\\APS Project\\sensor\\components\\data_transformation.py:79\u001b[0m, in \u001b[0;36mDataTransformation.initiate_data_transformation\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m     77\u001b[0m logging\u001b[38;5;241m.\u001b[39minfo(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mResampling completed\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m---> 79\u001b[0m train_arr \u001b[38;5;241m=\u001b[39m \u001b[43mnp\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mconcatenate\u001b[49m\u001b[43m(\u001b[49m\u001b[43minput_train_feature\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mnp\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43marray\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtarget_train_feature\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     80\u001b[0m logging\u001b[38;5;241m.\u001b[39minfo(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtrain array created successfully: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mtrain_arr\u001b[38;5;241m.\u001b[39mshape\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[1;32m<__array_function__ internals>:200\u001b[0m, in \u001b[0;36mconcatenate\u001b[1;34m(*args, **kwargs)\u001b[0m\n",
      "\u001b[1;31mTypeError\u001b[0m: only integer scalar arrays can be converted to a scalar index",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mSensorException\u001b[0m                           Traceback (most recent call last)",
      "File \u001b[1;32md:\\APS Project\\sensor\\pipeline\\training_pipeline.py:50\u001b[0m, in \u001b[0;36mTrainingPipeline.start_data_transformation\u001b[1;34m(self, data_validation_artifact)\u001b[0m\n\u001b[0;32m     49\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdata_transformation \u001b[38;5;241m=\u001b[39m DataTransformation(data_validation_artifact\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdata_validation_artifact,data_transformation_config\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdata_transformation_config)\n\u001b[1;32m---> 50\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdata_transformation_artifact \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mdata_transformation\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43minitiate_data_transformation\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     51\u001b[0m logging\u001b[38;5;241m.\u001b[39minfo(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mData transformation completed and artifact: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdata_transformation_artifact\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[1;32md:\\APS Project\\sensor\\components\\data_transformation.py:104\u001b[0m, in \u001b[0;36mDataTransformation.initiate_data_transformation\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    103\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m--> 104\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m SensorException(e,sys)\n",
      "\u001b[1;31mSensorException\u001b[0m: Error=[only integer scalar arrays can be converted to a scalar index] occurred in file [d:\\APS Project\\sensor\\components\\data_transformation.py] on line number [79]",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mSensorException\u001b[0m                           Traceback (most recent call last)",
      "File \u001b[1;32md:\\APS Project\\sensor\\pipeline\\training_pipeline.py:62\u001b[0m, in \u001b[0;36mTrainingPipeline.run_pipeline\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m     61\u001b[0m data_validation_artifact: DataValidationArtifact \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mstart_data_validation(data_ingestion_artifact)\n\u001b[1;32m---> 62\u001b[0m data_transformation_artifact: DataIngestionArtifact \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mstart_data_transformation\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdata_validation_artifact\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     63\u001b[0m logging\u001b[38;5;241m.\u001b[39minfo(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtraining pipeline completed\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[1;32md:\\APS Project\\sensor\\pipeline\\training_pipeline.py:55\u001b[0m, in \u001b[0;36mTrainingPipeline.start_data_transformation\u001b[1;34m(self, data_validation_artifact)\u001b[0m\n\u001b[0;32m     54\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m---> 55\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m SensorException(e,sys)\n",
      "\u001b[1;31mSensorException\u001b[0m: Error=[Error=[only integer scalar arrays can be converted to a scalar index] occurred in file [d:\\APS Project\\sensor\\components\\data_transformation.py] on line number [79]] occurred in file [d:\\APS Project\\sensor\\pipeline\\training_pipeline.py] on line number [50]",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mSensorException\u001b[0m                           Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[1], line 3\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01msensor\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mpipeline\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mtraining_pipeline\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m TrainingPipeline\n\u001b[0;32m      2\u001b[0m pp1 \u001b[38;5;241m=\u001b[39m TrainingPipeline()\n\u001b[1;32m----> 3\u001b[0m \u001b[43mpp1\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun_pipeline\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32md:\\APS Project\\sensor\\pipeline\\training_pipeline.py:67\u001b[0m, in \u001b[0;36mTrainingPipeline.run_pipeline\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m     65\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m data_transformation_artifact\n\u001b[0;32m     66\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m---> 67\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m SensorException(e,sys)\n",
      "\u001b[1;31mSensorException\u001b[0m: Error=[Error=[Error=[only integer scalar arrays can be converted to a scalar index] occurred in file [d:\\APS Project\\sensor\\components\\data_transformation.py] on line number [79]] occurred in file [d:\\APS Project\\sensor\\pipeline\\training_pipeline.py] on line number [50]] occurred in file [d:\\APS Project\\sensor\\pipeline\\training_pipeline.py] on line number [62]"
     ]
    }
   ],
   "source": [
    "from sensor.pipeline.training_pipeline import TrainingPipeline\n",
    "pp1 = TrainingPipeline()\n",
    "pp1.run_pipeline()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'df' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[3], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[43mdf\u001b[49m\n",
      "\u001b[1;31mNameError\u001b[0m: name 'df' is not defined"
     ]
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "np.c_()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "myenv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
